# Nixpacks configuration for Ative Run
[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[variables]
NODE_VERSION = "20.x"
PNPM_VERSION = "9"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install] 
cmds = ["cd apps/portal-web && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd apps/portal-web && pnpm run build"]

[start]
cmd = "cd apps/portal-web && pnpm start"

[phases.build]
cmds = ["pnpm run build:portal"]

[start]
cmd = "cd apps/portal-web && pnpm start"

[staticAssets]
# Serve static assets from the build
"apps/portal-web/.next/static" = "/_next/static"
"apps/portal-web/public" = "/"
